# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7cac119e3dbd870579ebdf5d2b60f04cfc8a96dd24ece3e17b88b7ec2c3182d03432211668496aa57d96a38a95e2c75c5d67c4f2d6a72fd987172f7975e72cd

test:
  secret_key_base: ec2201248da2f8b4805ff2396d51bd653dd0be1861bd57ac9d387387b89fe30b3d410d5996fbc664c4d00bddb778af1b8f4df5172c66aa3ad016c94b7e547ba4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
